### ISSUE TITLE
Location crash

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1033]

**Comment by ifoche** [comment]
04-03 07:48:44.528 30468-30468/org.eyeseetea.surveillance_kh_bb E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: org.eyeseetea.surveillance_kh_bb, PID: 30468
                                                                                  java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                                      at android.view.View.performClick(View.java:5246)
                                                                                      at android.view.View$PerformClick.run(View.java:21256)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6917)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                                      at android.view.View.performClick(View.java:5246) 
                                                                                      at android.view.View$PerformClick.run(View.java:21256) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6917) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
                                                                                      at org.eyeseetea.malariacare.strategies.ADashboardActivityStrategy.prepareLocationListener(ADashboardActivityStrategy.java:37)
                                                                                      at org.eyeseetea.malariacare.strategies.DashboardActivityStrategy.newSurvey(DashboardActivityStrategy.java:42)
                                                                                      at org.eyeseetea.malariacare.DashboardActivity.newSurvey(DashboardActivity.java:524)
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                                      at android.view.View.performClick(View.java:5246) 
                                                                                      at android.view.View$PerformClick.run(View.java:21256) 
                                                                                      at android.os.Handler.handleCallback(Handler.java:739) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6917) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
