### ISSUE TITLE
Bad credentials produce a crash

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1583]

**Comment by ifoche** [comment]
```
10-26 09:00:03.604 5868-13705/org.eyeseetea.surveillance_cnm_bb D/.LoginActivity: onInvalidCredentials
10-26 09:00:03.609 5868-13705/org.eyeseetea.surveillance_cnm_bb E/CrashlyticsCore: Failed to execute task.
                                                                                   java.lang.InterruptedException
                                                                                       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:391)
                                                                                       at java.util.concurrent.FutureTask.get(FutureTask.java:163)
                                                                                       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:47)
                                                                                       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
                                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:23dPoolExecutor.java:1133)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                      at java.lang.Thread.run(Thread.java:761)
                                                                                   Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
                                                                                      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:194)
                                                                                      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191)
                                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
                                                                                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                      at java.lang.Thread.run(Thread.java:761) 
                                                                                   Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
                                                                                      at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:194) 
                                                                                      at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120) 
                                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:191) 
                                                                                      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162) 
                                                                                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                      at java.lang.Thread.run(Thread.java:761) 
                                                                                   Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
                                                                                      at android.util.Log.printlns(Log.java:415)
                                                                                      at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
                                                                                      at com.android.internal.os.RuntimeInit.-wrap0(RuntimeInit.java)
                                                                                      at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:86)
                                                                                      at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:249)
                                                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                                                                                      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                                                                                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:66)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                      at java.lang.Thread.run(Thread.java:761) 
                                                                                   Caused by: org.hisp.dhis.client.sdk.core.common.network.ApiException: 401 Unauthorized
                                                                                      at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:179)
                                                                                      at org.hisp.dhis.client.sdk.android.user.UserAccountApiClientImpl.getUserAccount(UserAccountApiClientImpl.java:54)
                                                                                      at org.hisp.dhis.client.sdk.core.user.UserAccountControllerImpl.pull(UserAccountControllerImpl.java:73)
                                                                                      at org.hisp.dhis.client.sdk.android.user.CurrentUserInteractorImpl$1.call(CurrentUserInteractorImpl.java:94)
                                                                                      at org.hisp.dhis.client.sdk.android.user.CurrentUserInteractorImpl$1.call(CurrentUserInteractorImpl.java:84)
                                                                                      at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
                                                                                      at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
                                                                                      at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                                      at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:232)
                                                                                      at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:142)
                                                                                      at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
                                                                                      at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
                                                                                      at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
                                                                                      at rx.Observable$2.call(Observable.java:162)
                                                                                      at rx.Observable$2.call(Observable.java:154)
                                                                                      at rx.Observable$2.call(Observable.java:162)
                                                                                      at rx.Observable$2.call(Observable.java:154)
                                                                                      at rx.Observable.unsafeSubscribe(Observable.java:8098)
                                                                                      at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
                                                                                      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                      at java.lang.Thread.run(Thread.java:761) 

```

**Comment by idelcano** [comment]
Caused by: org.hisp.dhis.client.sdk.core.common.network.ApiException: 401 Unauthorized
         at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:179)
         at org.hisp.dhis.client.sdk.android.user.UserAccountApiClientImpl.getUserAccount(UserAccountApiClientImpl.java:54)
         at org.hisp.dhis.client.sdk.core.user.UserAccountControllerImpl.pull(UserAccountControllerImpl.java:73)
