### ISSUE TITLE
Memory leak on Progress Activity

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1614]

**Comment by idelcano** [comment]
10-27 17:36:16.699 org.eyeseetea.surveillance_cnm_bb E: android.view.WindowLeaked: Activity org.eyeseetea.malariacare.ProgressActivity has leaked window DecorView@404c742[ProgressActivity] that was originally added here
                                                            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:574)
                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:360)
                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
                                                            at android.app.Dialog.show(Dialog.java:404)
                                                            at org.eyeseetea.malariacare.ProgressActivity.showAndMoveOn(ProgressActivity.java:234)
                                                            at org.eyeseetea.malariacare.ProgressActivity.access$100(ProgressActivity.java:50)
                                                            at org.eyeseetea.malariacare.ProgressActivity$3.onComplete(ProgressActivity.java:148)
                                                            at org.eyeseetea.malariacare.domain.usecase.pull.PullUseCase$3.run(PullUseCase.java:95)
                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                            at android.os.Looper.loop(Looper.java:154)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

-----

ProgressActivity.showAndMoveOn(ProgressActivity.java:234)
                                                            at ProgressActivity.access$100(ProgressActivity.java:50)
                                                            at ProgressActivity$3.onComplete(ProgressActivity.java:148)
                                                            at domain.usecase.pull.PullUseCase$3.run(PullUseCase.java:95)
