### ISSUE TITLE
kill app + soft login doesn't work

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1774]
error:

```
01-25 12:47:40.984 4990-5036/org.eyeseetea.surveillance_ref_bb I/System.out: UserDB already savedUserDB{id_user_fk=0, uid='l1JeKsEo8G6', name='eref.webapp', mPartnerDB=0, supervisor=0, surveys=null, announcement=null, close_date=null, last_updated=null}
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: CountryVersion.uid (code 2067)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:77)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:110)
01-25 12:47:42.194 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:57)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.save(ModelSaver.java:40)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:102)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:51)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.metadata.configuration.MetadataConfigurationDBImporter.saveInDB(MetadataConfigurationDBImporter.java:155)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.metadata.configuration.MetadataConfigurationDBImporter.updateMetadataFor(MetadataConfigurationDBImporter.java:149)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.metadata.configuration.MetadataConfigurationDBImporter.processCountryData(MetadataConfigurationDBImporter.java:131)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.metadata.configuration.MetadataConfigurationDBImporter.importMetadata(MetadataConfigurationDBImporter.java:57)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.downloadMetadataFromConfigurationFiles(PullControllerStrategy.java:170)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.downloadMetadataAndRepopulateDB(PullControllerStrategy.java:146)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.checkNotSentSurveys(PullControllerStrategy.java:130)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.onPullDataComplete(PullControllerStrategy.java:107)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController$2.onSuccess(PullController.java:168)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController$2.onSuccess(PullController.java:165)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.remote.PullDhisSDKDataSource.pullData(PullDhisSDKDataSource.java:74)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController.pullData(PullController.java:164)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.pull(PullControllerStrategy.java:74)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController.pull(PullController.java:68)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.domain.usecase.pull.PullUseCase.run(PullUseCase.java:17)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.presentation.executors.AsyncExecutor$1.run(AsyncExecutor.java:40)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-25 12:47:42.195 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-25 12:47:42.196 4990-5036/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.lang.Thread.run(Thread.java:761)

```

config file is not updated

**Comment by ifoche** [comment]
Looks like a "fake" issue, resulting from executing the app while in staging variant
