### ISSUE TITLE
logoff + login doesn't work

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#1775]
```
01-25 12:51:03.879 4990-5569/org.eyeseetea.surveillance_ref_bb V/FlowLog: Executing query: SELECT * FROM `Program` WHERE `name`='T_TZ' LIMIT 1
01-25 12:51:03.881 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long org.eyeseetea.malariacare.data.database.model.ProgramDB.getId_program()' on a null object reference
01-25 12:51:03.881 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.database.datasources.ProgramLocalDataSource.saveUserProgramId(ProgramLocalDataSource.java:15)
01-25 12:51:03.881 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.onPullDataComplete(PullControllerStrategy.java:108)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController$2.onSuccess(PullController.java:168)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController$2.onSuccess(PullController.java:165)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.remote.PullDhisSDKDataSource.pullData(PullDhisSDKDataSource.java:74)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController.pullData(PullController.java:164)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.strategies.PullControllerStrategy.pull(PullControllerStrategy.java:74)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.data.sync.importer.PullController.pull(PullController.java:68)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.domain.usecase.pull.PullUseCase.run(PullUseCase.java:17)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at org.eyeseetea.malariacare.presentation.executors.AsyncExecutor$1.run(AsyncExecutor.java:40)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-25 12:51:03.882 4990-5569/org.eyeseetea.surveillance_ref_bb W/System.err:     at java.lang.Thread.run(Thread.java:761)

```

**Comment by ifoche** [comment]
Looks like a "fake" issue, resulting from executing the app while in staging variant
