### ISSUE TITLE
Investigate HTTP 500 Error on push to previous2 server

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2219]
The new app (v0.1_mtt branch) is properly in general but cannot push to the server due to a 500 HTTP error happening by the time of the push (server error). We need to investigate a bit more what's producing that error. Just for reference:

```
07-23 17:19:01.476 12930-13564/org.eyeseetea.surveillance_mtt_dev I/System.out: Error !(>= 200 && <300)https://play.dhis2.org/android-previous2/api/events
    {"httpStatus":"Internal Server Error","httpStatusCode":500,"status":"ERROR"}
07-23 17:19:01.477 12930-13564/org.eyeseetea.surveillance_mtt_dev W/System.err: java.io.IOException: Content-Length (76) and stream length (0) disagree
07-23 17:19:01.478 12930-13564/org.eyeseetea.surveillance_mtt_dev W/System.err:     at okhttp3.ResponseBody.bytes(ResponseBody.java:141)
        at org.hisp.dhis.client.sdk.android.api.network.ResponseMapper.fromRetrofitResponse(ResponseMapper.java:55)
        at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:181)
        at org.hisp.dhis.client.sdk.android.event.EventApiClientImpl.postEvents(EventApiClientImpl.java:88)
        at org.hisp.dhis.client.sdk.core.event.EventControllerImpl.sendEvents(EventControllerImpl.java:213)
07-23 17:19:01.479 12930-13564/org.eyeseetea.surveillance_mtt_dev W/System.err:     at org.hisp.dhis.client.sdk.core.event.EventControllerImpl.push(EventControllerImpl.java:192)
        at org.hisp.dhis.client.sdk.android.event.EventInteractorImpl$4.call(EventInteractorImpl.java:112)
        at org.hisp.dhis.client.sdk.android.event.EventInteractorImpl$4.call(EventInteractorImpl.java:108)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
07-23 17:19:01.480 12930-13564/org.eyeseetea.surveillance_mtt_dev W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
07-23 17:19:01.482 12930-13564/org.eyeseetea.surveillance_mtt_dev E/ApiException: HTTP error
    org.hisp.dhis.client.sdk.core.common.network.ApiException: 500 
        at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:179)
        at org.hisp.dhis.client.sdk.android.event.EventApiClientImpl.postEvents(EventApiClientImpl.java:88)
        at org.hisp.dhis.client.sdk.core.event.EventControllerImpl.sendEvents(EventControllerImpl.java:213)
        at org.hisp.dhis.client.sdk.core.event.EventControllerImpl.push(EventControllerImpl.java:192)
        at org.hisp.dhis.client.sdk.android.event.EventInteractorImpl$4.call(EventInteractorImpl.java:112)
        at org.hisp.dhis.client.sdk.android.event.EventInteractorImpl$4.call(EventInteractorImpl.java:108)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
07-23 17:19:01.483 12930-13557/org.eyeseetea.surveillance_mtt_dev W/System.err: org.hisp.dhis.client.sdk.core.common.network.ApiException: 500 
07-23 17:19:01.484 12930-13557/org.eyeseetea.surveillance_mtt_dev W/System.err:     at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:179)
        at org.hisp.dhis.client.sdk.android.event.EventApiClientImpl.postEvents(EventApiClientImpl.java:88)
        at org.hisp.dhis.client.sdk.core.event.EventControllerImpl.sendEvents(EventControllerImpl.java:213)
        at org.hisp.dhis.client.sdk.core.event.EventControllerImpl.push(EventControllerImpl.java:192)
        at org.hisp.dhis.client.sdk.android.event.EventInteractorImpl$4.call(EventInteractorImpl.java:112)
        at org.hisp.dhis.client.sdk.android.event.EventInteractorImpl$4.call(EventInteractorImpl.java:108)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
07-23 17:19:01.485 12930-13557/org.eyeseetea.surveillance_mtt_dev W/System.err:     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by xurxodev** [comment]
Seems an error with program d7iipQZaHad, this simple post fail with this program
{
  "event": "S1luRQwVLOL",
  "eventDate": "2018-07-26",
  "orgUnit": "DiszpKrYNg8",
  "program": "d7iipQZaHad",
  "status": "ACTIVE"
}
