### ISSUE TITLE
Crash after crash

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/pictureapp#2314]
## User Report
after a crash start a new survey and...

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot9201877916709665784.jpg)
## Device Info
```
Time Stamp: 2018-10-26T07:28:05 UTC
App Version: 0.5.0 (61)
Install Source: Unknown
Android Version: 8.1.0 (27)
Device Manufacturer: BQ
Device Model: AQUARIS X PRO
Display Resolution: 1920x1080
Display Density (Actual): 408dpi
Display Density (Bucket) Unknown
---------------------

```

**Comment by ifoche** [comment]
BTW I didn't copy the crash details, but just in case:
```
`ProgramProgramRelation` AS `pp` ON `pg`.`id_program`=`pp`.`id_aux_program` WHERE `pp`.`id_main_program`=3
2018-10-26 09:27:24.131 25949-25949/org.eyeseetea.surveillance_cnm_dev D/.SurveyFragment: onCreateView
2018-10-26 09:27:24.167 25949-25949/org.eyeseetea.surveillance_cnm_dev I/System.out: Exception info: Error loading new survey, null navigation controllerAttempt to invoke virtual method 'void org.eyeseetea.malariacare.layout.adapters.survey.navigation.NavigationController.first()' on a null object reference
2018-10-26 09:27:24.167 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eyeseetea.malariacare.layout.adapters.survey.navigation.NavigationController.first()' on a null object reference
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.layout.adapters.survey.DynamicTabAdapter.initNavigationController(DynamicTabAdapter.java:205)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.layout.adapters.survey.DynamicTabAdapter.<init>(DynamicTabAdapter.java:152)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.fragments.SurveyFragment$3.loadIsSurveyCreatedInOtherApp(SurveyFragment.java:231)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.strategies.SurveyFragmentStrategy.isSurveyCreatedFromOtherApp(SurveyFragmentStrategy.java:105)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.fragments.SurveyFragment.showSurvey(SurveyFragment.java:225)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.fragments.SurveyFragment.initializeSurvey(SurveyFragment.java:207)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at org.eyeseetea.malariacare.fragments.SurveyFragment.onCreateView(SurveyFragment.java:108)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.Fragment.performCreateView(Fragment.java:2508)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
2018-10-26 09:27:24.168 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.os.Looper.loop(Looper.java:164)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6518)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2018-10-26 09:27:24.169 25949-25949/org.eyeseetea.surveillance_cnm_dev W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                                                                            370,1         Bot
```
