### ISSUE TITLE
Android 5.1.1 crashes right after the splash screen

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2331]
Crash trace:

```
11-14 11:24:57.508 6819-6819/org.eyeseetea.surveillance_ref_dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.eyeseetea.surveillance_ref_dev, PID: 6819
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzac;
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6458)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6053)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5993)
        at android.app.ActivityThread.access$1700(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6917)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzac" on path: DexPathList[[zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/base.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.eyeseetea.surveillance_ref_dev-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.eyeseetea.surveillance_ref_dev-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6458) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6053) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5993) 
        at android.app.ActivityThread.access$1700(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6917) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.zzac
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 15 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by manuelplazaspalacio** [comment]
Crashing when launching from ide but with an apk not generated by yuor ide works well.
