### ISSUE TITLE
Android < 8.0 fails with a crash

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/pictureapp#2372]
Right after installing it and while in splash screen

```
01-30 23:40:19.749 17884-17932/org.eyeseetea.surveillance_ref_dev E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.eyeseetea.surveillance_ref_dev, PID: 17884
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6426)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:984)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:4638)
        at android.view.View.invalidateInternal(View.java:11731)
        at android.view.View.invalidate(View.java:11695)
        at android.view.View.invalidate(View.java:11679)
        at android.widget.TextView.checkForRelayout(TextView.java:7049)
        at android.widget.TextView.setText(TextView.java:4189)
        at android.widget.TextView.setText(TextView.java:4047)
        at android.widget.TextView.setText(TextView.java:4002)
        at org.eyeseetea.sdk.presentation.views.CustomViewTranslationHelper.translateText(CustomViewTranslationHelper.java:37)
        at org.eyeseetea.sdk.presentation.views.CustomTextView.setTextTranslation(CustomTextView.java:43)
        at org.eyeseetea.malariacare.strategies.SplashActivityStrategy.showProgressMessage(SplashActivityStrategy.java:229)
        at org.eyeseetea.malariacare.SplashScreenActivity.init(SplashScreenActivity.java:81)
        at org.eyeseetea.malariacare.SplashScreenActivity.access$100(SplashScreenActivity.java:21)
        at org.eyeseetea.malariacare.SplashScreenActivity$AsyncInitApplication.doInBackground(SplashScreenActivity.java:102)
        at org.eyeseetea.malariacare.SplashScreenActivity$AsyncInitApplication.doInBackground(SplashScreenActivity.java:88)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by ifoche** [comment]
7.x & 5.0.1 Android crash
